spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=niteenjha190@gmail.com
spring.mail.password=haqfddznribddvaj
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.writetimeout=15000
server.port=${PORT:8080}
