resend.api.key=${RESEND_API_KEY:re_AA9pMs2i_8j26xoHnYXPBj1opkbyv7g8p}
resend.from.email=${RESEND_FROM_EMAIL:Portfolio Contact <onboarding@resend.dev>}
contact.recipient.email=${CONTACT_RECIPIENT_EMAIL:niteenjha190@gmail.com}

server.port=${PORT:8080}
